namespace: dev

backend:
  replicaCount: 3
  image: simbadata/devops-backend:latest

frontend:
  replicaCount: 1
  image: simbadata/devops-frontend:latest

postgres:
  storageSize: 1Gi
  image: postgres:15
